using Dapper;
using ModsWatcher.Core.Entities;
using ModsWatcher.Core.Enums;
using ModsWatcher.Core.Interfaces;
using ModsWatcher.Data;
using Moq;
using System.Data;
using Xunit;

namespace ModsWatcher.Tests.Repos
{
    public class InstalledModRepositoryTests : BaseRepositoryTest
    {
        private readonly InstalledModRepository _repo;
        private readonly Mock<IModRepository> _modRepoMock;

        public InstalledModRepositoryTests()
        {
            _modRepoMock = new Mock<IModRepository>();
            _repo = new InstalledModRepository(FactoryMock.Object, _modRepoMock.Object);
        }

        private async Task<(int AppId, Guid ModId)> SeedDatabaseAsync()
        {
            const string appSql = "INSERT INTO ModdedApp (Name) VALUES ('Skyrim'); SELECT last_insert_rowid();";
            int appId = await Connection.QuerySingleAsync<int>(appSql);

            Guid modId = Guid.NewGuid();
            const string modSql = "INSERT INTO Mod (Id, AppId, Name, IsUsed, IsDeprecated) VALUES (@Id, @AppId, 'SkyUI', 1, 0)";
            await Connection.ExecuteAsync(modSql, new { Id = modId, AppId = appId });

            return (appId, modId);
        }

        [Fact]
        public async Task InsertAsync_ShouldCreateInstalledMod_AndHandleExistingModCheck()
        {
            // Arrange
            var ids = await SeedDatabaseAsync();
            var installedMod = new InstalledMod
            {
                Id = ids.ModId,
                InstalledVersion = "5.2",
                InstalledDate = DateOnly.FromDateTime(DateTime.UtcNow),
                PackageType = PackageType.Zip
            };

            // Setup: Simulate Mod already exists
            _modRepoMock.Setup(m => m.GetByIdAsync(ids.ModId, It.IsAny<IDbConnection>(), It.IsAny<IDbTransaction>(), default))
                        .ReturnsAsync(new Mod { Id = ids.ModId });

            // Act
            await _repo.InsertAsync(installedMod, Connection);

            // Assert
            var result = await _repo.FindByModIdAsync(ids.ModId, Connection);
            Assert.NotNull(result);
            Assert.Equal(ids.ModId, result.Id);
            _modRepoMock.Verify(m => m.InsertAsync(It.IsAny<Mod>(), It.IsAny<IDbConnection>(), It.IsAny<IDbTransaction>(), default), Times.Never);
        }

        [Fact]
        public async Task InsertAsync_ShouldInvokeModInsert_WhenModIsMissing()
        {
            // Arrange
            var modId = Guid.NewGuid();
            var installedMod = new InstalledMod { Id = modId, InstalledVersion = "1.0", AppId = 1 };

            // Seed the parent App first so the Mod insert doesn't fail its own FK check
            await Connection.ExecuteAsync("INSERT INTO ModdedApp (Id, Name) VALUES (1, 'Test')");

            _modRepoMock.Setup(m => m.GetByIdAsync(modId, It.IsAny<IDbConnection>(), It.IsAny<IDbTransaction>(), default))
                        .ReturnsAsync((Mod)null);

            // FIX: When the mock is called, actually perform the SQL insert so the FK constraint is satisfied
            _modRepoMock.Setup(m => m.InsertAsync(It.IsAny<Mod>(), It.IsAny<IDbConnection>(), It.IsAny<IDbTransaction>(), default))
                        .Returns<Mod, IDbConnection, IDbTransaction, CancellationToken>(async (m, conn, trans, token) =>
                        {
                            await conn.ExecuteAsync("INSERT INTO Mod (Id, AppId, Name, IsUsed, IsDeprecated) VALUES (@Id, @AppId, 'AutoGenerated', 1, 0)", m, trans);
                            return m;
                        });

            // Act
            await _repo.InsertAsync(installedMod, Connection);

            // Assert
            _modRepoMock.Verify(m => m.InsertAsync(It.IsAny<Mod>(), It.IsAny<IDbConnection>(), It.IsAny<IDbTransaction>(), default), Times.Once);

            var exists = await Connection.ExecuteScalarAsync<bool>("SELECT 1 FROM InstalledMod WHERE ModId = @Id", new { Id = modId });
            Assert.True(exists);
        }

        [Fact]
        public async Task UpdateAsync_ShouldPersistChanges_WithCorrectByteCast()
        {
            // Arrange
            var ids = await SeedDatabaseAsync();
            await Connection.ExecuteAsync("INSERT INTO InstalledMod (ModId, InstalledVersion, PackageType) VALUES (@ModId, '1.0', 1)", new { ModId = ids.ModId });

            var update = new InstalledMod
            {
                Id = ids.ModId,
                InstalledVersion = "2.0",
                PackageType = PackageType.Rar // Rar = 2
            };

            // Act
            await _repo.UpdateAsync(update, Connection);

            // Assert
            var result = await _repo.FindByModIdAsync(ids.ModId, Connection);
            Assert.Equal("2.0", result.InstalledVersion);
            Assert.Equal(PackageType.Rar, result.PackageType);
        }

        [Fact]
        public async Task GetByIdAsync_ShouldReturnJoinedData_ByInternalId()
        {
            // Arrange
            var ids = await SeedDatabaseAsync();
            await Connection.ExecuteAsync("INSERT INTO InstalledMod (ModId, InstalledVersion) VALUES (@ModId, '1.1')", new { ModId = ids.ModId });
            int internalId = await Connection.ExecuteScalarAsync<int>("SELECT last_insert_rowid()");

            // Act
            var result = await _repo.GetByIdAsync(internalId, Connection);

            // Assert
            Assert.NotNull(result);
            Assert.Equal("SkyUI", result.Name); // Verifies JOIN logic
            Assert.Equal(ids.ModId, result.Id);   // Verifies Guid mapping
        }

        [Fact]
        public async Task QueryAllAsync_ShouldReturnEmpty_WhenNoInstallationsExist()
        {
            // Act
            var results = await _repo.QueryAllAsync(Connection);

            // Assert
            Assert.Empty(results);
        }

        [Fact]
        public async Task DeleteByModIdAsync_ShouldReturnTrue_OnSuccess()
        {
            // Arrange
            var ids = await SeedDatabaseAsync();
            await Connection.ExecuteAsync("INSERT INTO InstalledMod (ModId) VALUES (@ModId)", new { ModId = ids.ModId });

            // Act
            var result = await _repo.DeleteByModIdAsync(ids.ModId, Connection);

            // Assert
            Assert.True(result);
            var exists = await Connection.ExecuteScalarAsync<bool>("SELECT 1 FROM InstalledMod WHERE ModId = @Id", new { Id = ids.ModId });
            Assert.False(exists);
        }

        [Fact]
        public async Task DeleteByAppIdAsync_ShouldWipeAllModsInApp()
        {
            // Arrange
            var ids = await SeedDatabaseAsync();
            await Connection.ExecuteAsync("INSERT INTO InstalledMod (ModId) VALUES (@ModId)", new { ModId = ids.ModId });

            // Act
            var result = await _repo.DeleteByAppIdAsync(ids.AppId, Connection);

            // Assert
            Assert.True(result);
            var count = await Connection.ExecuteScalarAsync<int>("SELECT COUNT(1) FROM InstalledMod");
            Assert.Equal(0, count);
        }
    }
}